import { PersonaScenario, Income, Expense, BudgetCategory, SavingsGoal } from '../types';

export const PERSONA_SCENARIOS: PersonaScenario[] = [
  {
    id: 'salaried',
    title: 'Scenario 1: Salaried Professional',
    personaName: 'Elena Vance',
    role: 'Senior Software Engineer',
    scenarioSummary: 'Fixed monthly paycheck. Tracks daily living costs, detects lifestyle creep in dining & entertainment, and optimizes investments.',
    avatar: '👩‍💼',
    badge: 'Fixed Income & Overspending Control',
    defaultCurrency: 'USD',
    keyFocus: ['Overspending Detection in Dining', '50/30/20 Budget Optimization', 'Automated Index Fund Investing'],
    recommendedStrategy: 'Automate a 20% direct deposit into savings before discretionary spending, and cap dining out to $120/week.',
  },
  {
    id: 'student',
    title: 'Scenario 2: College Student',
    personaName: 'Liam Chen',
    role: 'Computer Science Undergrad',
    scenarioSummary: 'Strict allowance & campus job. Eliminates impulse spend on coffees and late-night food, setting disciplined saving habits.',
    avatar: '🎓',
    badge: 'Tight Allowance & Frugal Habits',
    defaultCurrency: 'USD',
    keyFocus: ['Discretionary Spend Trimming', 'Textbook & Campus Cost Control', 'First $1,000 Emergency Fund'],
    recommendedStrategy: 'Leverage student discounts, meal prep twice a week to halve dining costs, and maintain a $100 monthly cash safety cushion.',
  },
  {
    id: 'freelancer',
    title: 'Scenario 3: Variable Income Freelancer',
    personaName: 'Maya Lin',
    role: 'Independent Brand Designer',
    scenarioSummary: 'Fluctuating client earnings across multiple accounts. Manages project expenses, isolates tax reserves, and builds a 6-month lean runway.',
    avatar: '💻',
    badge: 'Multi-Client & Variable Cashflow',
    defaultCurrency: 'USD',
    keyFocus: ['Income Volatility Smoothing', '25-30% Tax Reserve Isolation', '6-Month Emergency Runway'],
    recommendedStrategy: 'Base living expenses on your lowest earning month ($3,200), sweeping windfall client retainers straight into your tax & runway accounts.',
  },
  {
    id: 'household',
    title: 'Scenario 4: Household Family Manager',
    personaName: 'Carlos & Priya Morales',
    role: 'Dual-Earner Household (Family of 4)',
    scenarioSummary: 'Consolidated family finances spanning groceries, childcare, healthcare, plus international remittances across USD, EUR, and INR.',
    avatar: '👨‍👩‍👧‍👦',
    badge: 'Multi-Earner & Multi-Currency',
    defaultCurrency: 'USD',
    keyFocus: ['Bulk Family Grocery Optimization', 'Childcare & Healthcare Planning', 'Cross-Border Remittances (EUR/INR)'],
    recommendedStrategy: 'Unify monthly recurring utilities, schedule weekly meal shopping with strict lists, and monitor FX exchange rates for overseas remittances.',
  },
];

export const INITIAL_SCENARIO_DATA: Record<
  string,
  {
    incomes: Income[];
    expenses: Expense[];
    budgets: BudgetCategory[];
    goals: SavingsGoal[];
    currency: string;
  }
> = {
  salaried: {
    currency: 'USD',
    incomes: [
      {
        id: 'inc-sal-1',
        source: 'Apex Technologies (Base Salary)',
        amount: 5200,
        category: 'Salary',
        date: '2026-09-01',
        frequency: 'monthly',
        currency: 'USD',
        notes: 'Net direct deposit after 401(k) and health deductions',
      },
      {
        id: 'inc-sal-2',
        source: 'Index Fund Dividend Distribution',
        amount: 320,
        category: 'Investment',
        date: '2026-09-15',
        frequency: 'monthly',
        currency: 'USD',
        notes: 'Vanguard quarterly dividend payout',
      },
    ],
    expenses: [
      {
        id: 'exp-sal-1',
        description: 'Luxury Apartment Rent (Downtown)',
        amount: 1650,
        category: 'Housing',
        date: '2026-09-01',
        isEssential: true,
        paymentMethod: 'Bank Transfer',
        currency: 'USD',
      },
      {
        id: 'exp-sal-2',
        description: 'Supermarket Grocery Haul',
        amount: 340,
        category: 'Food & Groceries',
        date: '2026-09-04',
        isEssential: true,
        paymentMethod: 'Credit Card',
        currency: 'USD',
      },
      {
        id: 'exp-sal-3',
        description: 'Fine Dining & Weekend Cocktails',
        amount: 390,
        category: 'Food & Groceries',
        date: '2026-09-12',
        isEssential: false,
        paymentMethod: 'Credit Card',
        currency: 'USD',
        notes: 'Dinner with coworkers at upscale bistro (over budget)',
      },
      {
        id: 'exp-sal-4',
        description: 'Metro Monthly Transit Pass & Uber Rides',
        amount: 280,
        category: 'Transport',
        date: '2026-09-05',
        isEssential: true,
        paymentMethod: 'Credit Card',
        currency: 'USD',
      },
      {
        id: 'exp-sal-5',
        description: 'Concert Tickets & VIP Lounge',
        amount: 430,
        category: 'Entertainment',
        date: '2026-09-18',
        isEssential: false,
        paymentMethod: 'Credit Card',
        currency: 'USD',
        notes: 'Weekend music festival pass (overspending alert)',
      },
      {
        id: 'exp-sal-6',
        description: 'Electric, Water, & Gigabit Fiber Internet',
        amount: 210,
        category: 'Utilities',
        date: '2026-09-10',
        isEssential: true,
        paymentMethod: 'Bank Transfer',
        currency: 'USD',
      },
      {
        id: 'exp-sal-7',
        description: 'Equinox Gym & Pilates Subscription',
        amount: 145,
        category: 'Healthcare',
        date: '2026-09-02',
        isEssential: false,
        paymentMethod: 'Credit Card',
        currency: 'USD',
      },
      {
        id: 'exp-sal-8',
        description: 'Streaming & Cloud Storage Services',
        amount: 65,
        category: 'Entertainment',
        date: '2026-09-08',
        isEssential: false,
        paymentMethod: 'Credit Card',
        currency: 'USD',
      },
    ],
    budgets: [
      { id: 'b-sal-1', category: 'Housing', budgetLimit: 1700, period: 'monthly', color: '#3b82f6', rationale: 'Fixed lease commitment' },
      { id: 'b-sal-2', category: 'Food & Groceries', budgetLimit: 550, period: 'monthly', color: '#10b981', rationale: 'Target groceries & light dining' },
      { id: 'b-sal-3', category: 'Transport', budgetLimit: 300, period: 'monthly', color: '#f59e0b', rationale: 'Transit & occasional ride-hails' },
      { id: 'b-sal-4', category: 'Entertainment', budgetLimit: 300, period: 'monthly', color: '#ec4899', rationale: 'Concerts & discretionary outings' },
      { id: 'b-sal-5', category: 'Utilities', budgetLimit: 220, period: 'monthly', color: '#8b5cf6', rationale: 'Power, water, web' },
      { id: 'b-sal-6', category: 'Healthcare', budgetLimit: 180, period: 'monthly', color: '#06b6d4', rationale: 'Gym & prescriptions' },
    ],
    goals: [
      {
        id: 'g-sal-1',
        title: '6-Month Emergency Cushion',
        targetAmount: 18000,
        currentAmount: 13200,
        targetDate: '2027-03-31',
        category: 'emergency',
        notes: 'High-yield savings account for complete career safety',
      },
      {
        id: 'g-sal-2',
        title: 'Condo Down Payment',
        targetAmount: 50000,
        currentAmount: 22400,
        targetDate: '2028-06-30',
        category: 'housing',
        notes: 'Target 20% down on 2-bedroom home',
      },
    ],
  },

  student: {
    currency: 'USD',
    incomes: [
      {
        id: 'inc-stu-1',
        source: 'Monthly Family Allowance Support',
        amount: 650,
        category: 'Allowance',
        date: '2026-09-01',
        frequency: 'monthly',
        currency: 'USD',
      },
      {
        id: 'inc-stu-2',
        source: 'Computer Science TA Stipend (10 hrs/wk)',
        amount: 380,
        category: 'Side Gig',
        date: '2026-09-15',
        frequency: 'monthly',
        currency: 'USD',
      },
    ],
    expenses: [
      {
        id: 'exp-stu-1',
        description: 'University Co-Op Student Room Shared Rent',
        amount: 460,
        category: 'Housing',
        date: '2026-09-01',
        isEssential: true,
        paymentMethod: 'Bank Transfer',
        currency: 'USD',
      },
      {
        id: 'exp-stu-2',
        description: 'Campus Dining Hall Meals & Value Groceries',
        amount: 220,
        category: 'Food & Groceries',
        date: '2026-09-06',
        isEssential: true,
        paymentMethod: 'Debit Card',
        currency: 'USD',
      },
      {
        id: 'exp-stu-3',
        description: 'Daily Cafe Mochas & Late Night Pizza',
        amount: 115,
        category: 'Food & Groceries',
        date: '2026-09-14',
        isEssential: false,
        paymentMethod: 'Debit Card',
        currency: 'USD',
        notes: 'Discretionary takeout with study group (cutting recommended)',
      },
      {
        id: 'exp-stu-4',
        description: 'Algorithms Textbook Rental & Course Lab Pack',
        amount: 75,
        category: 'Education',
        date: '2026-09-04',
        isEssential: true,
        paymentMethod: 'Debit Card',
        currency: 'USD',
      },
      {
        id: 'exp-stu-5',
        description: 'Weekend Cinema & Esports Tournament Pass',
        amount: 60,
        category: 'Entertainment',
        date: '2026-09-20',
        isEssential: false,
        paymentMethod: 'Debit Card',
        currency: 'USD',
      },
      {
        id: 'exp-stu-6',
        description: 'Campus Student Bus Pass Recharge',
        amount: 30,
        category: 'Transport',
        date: '2026-09-02',
        isEssential: true,
        paymentMethod: 'Debit Card',
        currency: 'USD',
      },
    ],
    budgets: [
      { id: 'b-stu-1', category: 'Housing', budgetLimit: 480, period: 'monthly', color: '#3b82f6', rationale: 'Dorm & shared utilities' },
      { id: 'b-stu-2', category: 'Food & Groceries', budgetLimit: 250, period: 'monthly', color: '#10b981', rationale: 'Meals & cooking' },
      { id: 'b-stu-3', category: 'Education', budgetLimit: 90, period: 'monthly', color: '#8b5cf6', rationale: 'Books and stationery' },
      { id: 'b-stu-4', category: 'Entertainment', budgetLimit: 50, period: 'monthly', color: '#ec4899', rationale: 'Social activities' },
      { id: 'b-stu-5', category: 'Transport', budgetLimit: 35, period: 'monthly', color: '#f59e0b', rationale: 'Campus shuttle pass' },
    ],
    goals: [
      {
        id: 'g-stu-1',
        title: 'Emergency Student Safety Cushion',
        targetAmount: 1000,
        currentAmount: 420,
        targetDate: '2026-12-15',
        category: 'emergency',
        notes: 'Covers unexpected medical copays or tech repairs',
      },
      {
        id: 'g-stu-2',
        title: 'New Coding Laptop Fund',
        targetAmount: 1200,
        currentAmount: 510,
        targetDate: '2027-05-30',
        category: 'equipment',
        notes: 'MacBook Air upgrade for senior year projects',
      },
    ],
  },

  freelancer: {
    currency: 'USD',
    incomes: [
      {
        id: 'inc-fre-1',
        source: 'FinTech Startup Mobile App UI Design',
        amount: 2300,
        category: 'Freelance',
        date: '2026-09-04',
        frequency: 'one-time',
        currency: 'USD',
        notes: 'Milestone 2 completion payment',
      },
      {
        id: 'inc-fre-2',
        source: 'Nordic Brand Identity System',
        amount: 1650,
        category: 'Freelance',
        date: '2026-09-16',
        frequency: 'one-time',
        currency: 'USD',
        notes: 'Contract deposit via Wire transfer',
      },
      {
        id: 'inc-fre-3',
        source: 'Design Retainer - Studio Velocity',
        amount: 950,
        category: 'Freelance',
        date: '2026-09-01',
        frequency: 'monthly',
        currency: 'USD',
        notes: 'Recurring monthly maintenance retainer',
      },
    ],
    expenses: [
      {
        id: 'exp-fre-1',
        description: 'Home Studio & Living Apartment Rent',
        amount: 1450,
        category: 'Housing',
        date: '2026-09-01',
        isEssential: true,
        paymentMethod: 'Bank Transfer',
        currency: 'USD',
        notes: '30% tax deductible as home office space',
      },
      {
        id: 'exp-fre-2',
        description: 'Figma Organization & Adobe Creative Cloud',
        amount: 110,
        category: 'Software & Tools',
        date: '2026-09-03',
        isEssential: true,
        paymentMethod: 'Credit Card',
        currency: 'USD',
        notes: 'Essential design software toolchain',
      },
      {
        id: 'exp-fre-3',
        description: 'AWS Cloud Hosting & Client Showcase Domains',
        amount: 45,
        category: 'Software & Tools',
        date: '2026-09-05',
        isEssential: true,
        paymentMethod: 'Credit Card',
        currency: 'USD',
      },
      {
        id: 'exp-fre-4',
        description: 'WeWork Hotdesk Membership (Client Meetings)',
        amount: 275,
        category: 'Software & Tools',
        date: '2026-09-02',
        isEssential: false,
        paymentMethod: 'Credit Card',
        currency: 'USD',
      },
      {
        id: 'exp-fre-5',
        description: 'Freelancer Private Health Insurance Policy',
        amount: 360,
        category: 'Healthcare',
        date: '2026-09-07',
        isEssential: true,
        paymentMethod: 'Bank Transfer',
        currency: 'USD',
      },
      {
        id: 'exp-fre-6',
        description: 'Groceries & Home Office Lunches',
        amount: 520,
        category: 'Food & Groceries',
        date: '2026-09-11',
        isEssential: true,
        paymentMethod: 'Credit Card',
        currency: 'USD',
      },
      {
        id: 'exp-fre-7',
        description: 'Client Dinners & Industry Networking',
        amount: 240,
        category: 'Entertainment',
        date: '2026-09-22',
        isEssential: false,
        paymentMethod: 'Credit Card',
        currency: 'USD',
      },
    ],
    budgets: [
      { id: 'b-fre-1', category: 'Housing', budgetLimit: 1500, period: 'monthly', color: '#3b82f6', rationale: 'Home office living base' },
      { id: 'b-fre-2', category: 'Software & Tools', budgetLimit: 400, period: 'monthly', color: '#8b5cf6', rationale: 'Design SaaS & desk passes' },
      { id: 'b-fre-3', category: 'Healthcare', budgetLimit: 380, period: 'monthly', color: '#06b6d4', rationale: 'Self-employed insurance' },
      { id: 'b-fre-4', category: 'Food & Groceries', budgetLimit: 550, period: 'monthly', color: '#10b981', rationale: 'Home meals and coffee' },
      { id: 'b-fre-5', category: 'Entertainment', budgetLimit: 250, period: 'monthly', color: '#ec4899', rationale: 'Networking & leisure' },
      { id: 'b-fre-6', category: 'Tax Reserve', budgetLimit: 1250, period: 'monthly', color: '#f59e0b', rationale: 'Set aside 25% for IRS' },
    ],
    goals: [
      {
        id: 'g-fre-1',
        title: 'Q3 Estimated Tax Withholding',
        targetAmount: 4200,
        currentAmount: 3300,
        targetDate: '2026-10-15',
        category: 'debt',
        notes: 'Strictly untouched tax reserve bank account',
      },
      {
        id: 'g-fre-2',
        title: '6-Month Lean Runway Buffer',
        targetAmount: 18000,
        currentAmount: 11400,
        targetDate: '2027-02-28',
        category: 'emergency',
        notes: 'Guarantees uninterrupted business during dry contract months',
      },
    ],
  },

  household: {
    currency: 'USD',
    incomes: [
      {
        id: 'inc-hou-1',
        source: 'Carlos Senior Engineering Salary',
        amount: 4900,
        category: 'Salary',
        date: '2026-09-01',
        frequency: 'monthly',
        currency: 'USD',
        notes: 'Primary earner bi-weekly consolidated direct deposit',
      },
      {
        id: 'inc-hou-2',
        source: 'Priya Senior Financial Analyst Salary',
        amount: 4100,
        category: 'Partner Income',
        date: '2026-09-01',
        frequency: 'monthly',
        currency: 'USD',
        notes: 'Secondary earner salary deposited into joint account',
      },
      {
        id: 'inc-hou-3',
        source: 'Family Rental Property Dividend',
        amount: 600,
        category: 'Investment',
        date: '2026-09-10',
        frequency: 'monthly',
        currency: 'USD',
        notes: 'Net proceeds from shared multi-family property',
      },
    ],
    expenses: [
      {
        id: 'exp-hou-1',
        description: 'Family 4-Bedroom Home Mortgage & Property Tax',
        amount: 2650,
        category: 'Housing',
        date: '2026-09-01',
        isEssential: true,
        paymentMethod: 'Bank Transfer',
        currency: 'USD',
      },
      {
        id: 'exp-hou-2',
        description: 'Costco & Whole Foods Family Groceries',
        amount: 1380,
        category: 'Food & Groceries',
        date: '2026-09-07',
        isEssential: true,
        paymentMethod: 'Credit Card',
        currency: 'USD',
        notes: 'Overspending alert! High premium organic purchases ($180 above budget)',
      },
      {
        id: 'exp-hou-3',
        description: 'Dual Montessori Daycare & Kids STEM After-School',
        amount: 1450,
        category: 'Education',
        date: '2026-09-03',
        isEssential: true,
        paymentMethod: 'Bank Transfer',
        currency: 'USD',
      },
      {
        id: 'exp-hou-4',
        description: 'Family Health Insurance Plan & Pediatrician Checkups',
        amount: 520,
        category: 'Healthcare',
        date: '2026-09-12',
        isEssential: true,
        paymentMethod: 'Bank Transfer',
        currency: 'USD',
      },
      {
        id: 'exp-hou-5',
        description: 'Power, Gas, Water, Trash, & High-Speed Fiber',
        amount: 395,
        category: 'Utilities',
        date: '2026-09-09',
        isEssential: true,
        paymentMethod: 'Bank Transfer',
        currency: 'USD',
      },
      {
        id: 'exp-hou-6',
        description: 'Family Minivan Fuel, Insurance, & Maintenance',
        amount: 360,
        category: 'Transport',
        date: '2026-09-15',
        isEssential: true,
        paymentMethod: 'Credit Card',
        currency: 'USD',
      },
      {
        id: 'exp-hou-7',
        description: 'Grandparents Support Remittance to Spain (Madrid)',
        amount: 650,
        category: 'Family Remittance',
        date: '2026-09-05',
        isEssential: true,
        paymentMethod: 'Bank Transfer',
        currency: 'EUR',
        notes: 'Converted 600 EUR at 1.08 exchange rate for elder healthcare support',
      },
      {
        id: 'exp-hou-8',
        description: 'Weekend Family Bowling, Pizza, & Kids Toys',
        amount: 290,
        category: 'Entertainment',
        date: '2026-09-19',
        isEssential: false,
        paymentMethod: 'Credit Card',
        currency: 'USD',
      },
    ],
    budgets: [
      { id: 'b-hou-1', category: 'Housing', budgetLimit: 2700, period: 'monthly', color: '#3b82f6', rationale: 'Mortgage & escrow property tax' },
      { id: 'b-hou-2', category: 'Food & Groceries', budgetLimit: 1200, period: 'monthly', color: '#10b981', rationale: 'Household pantry & weekly meal shopping' },
      { id: 'b-hou-3', category: 'Education', budgetLimit: 1500, period: 'monthly', color: '#8b5cf6', rationale: 'Childcare, Montessori, clubs' },
      { id: 'b-hou-4', category: 'Healthcare', budgetLimit: 550, period: 'monthly', color: '#06b6d4', rationale: 'Family coverage & prescription co-pays' },
      { id: 'b-hou-5', category: 'Utilities', budgetLimit: 420, period: 'monthly', color: '#6366f1', rationale: 'Full house utilities' },
      { id: 'b-hou-6', category: 'Transport', budgetLimit: 380, period: 'monthly', color: '#f59e0b', rationale: 'Family vehicles & fuel' },
      { id: 'b-hou-7', category: 'Family Remittance', budgetLimit: 700, period: 'monthly', color: '#ec4899', rationale: 'Elder parent cross-border support' },
      { id: 'b-hou-8', category: 'Entertainment', budgetLimit: 300, period: 'monthly', color: '#14b8a6', rationale: 'Weekend family leisure' },
    ],
    goals: [
      {
        id: 'g-hou-1',
        title: 'Twins College 529 Investment Fund',
        targetAmount: 50000,
        currentAmount: 26800,
        targetDate: '2030-08-31',
        category: 'education',
        notes: 'Tax-advantaged state college investment growth plan',
      },
      {
        id: 'g-hou-2',
        title: 'Household Safety & Home Repair Buffer',
        targetAmount: 30000,
        currentAmount: 21500,
        targetDate: '2027-04-30',
        category: 'emergency',
        notes: '6-month joint family reserves for roof, HVAC, or job transition',
      },
      {
        id: 'g-hou-3',
        title: 'International Family Reunion (Spain & India)',
        targetAmount: 7500,
        currentAmount: 4800,
        targetDate: '2027-07-15',
        category: 'vacation',
        notes: 'Flights and accommodation for 3-week extended family visit',
      },
    ],
  },
};

export const COMMON_CATEGORIES = [
  'Housing',
  'Food & Groceries',
  'Transport',
  'Utilities',
  'Entertainment',
  'Healthcare',
  'Education',
  'Software & Tools',
  'Family Remittance',
  'Tax Reserve',
  'Shopping',
  'Savings & Investments',
  'Other',
];

export const CURRENCY_SYMBOLS: Record<string, string> = {
  USD: '$',
  EUR: '€',
  GBP: '£',
  INR: '₹',
  JPY: '¥',
  CAD: 'C$',
  AUD: 'A$',
  SGD: 'S$',
  AED: 'AED ',
  CHF: 'CHF ',
  CNY: '¥',
  BRL: 'R$',
};
